### ISSUE TITLE
Console error spam

### ISSUE THREAD

**Issue by NEXUS2345** [JimiIT92/UniverseGuard#1]
Using plugin on SpongeVanilla 5.2.0 beta 385 on 1.10.2 with version 1.2 of the plugin and seeing the following spammed constantly:

`[15:13:36] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=universeguard, name=Universe Guard, version=1.0, description=A World Guard solution for Sponge, source=mods/Universe Guard 1.2
.jar}
java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_121]
    at com.universeguard.utils.Utils.isSelector(Utils.java:41) ~[Utils.class:?]
    at com.universeguard.events.EventRightClick.onRightClickMainHand(EventRightClick.java:25) ~[EventRightClick.class:?]
    at org.spongepowered.common.event.listener.MainHandListener_EventRightClick_onRightClickMainHand17.handle(Unknown Source) ~[?:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-5.2.0-BETA-385]
    at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305) ~[SpongeEventManager.class:1.10.2-5.2.0-BETA-385]
    at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320) ~[SpongeEventManager.class:1.10.2-5.2.0-BETA-385]
    at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-5.2.0-BETA-385]
    at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:459) ~[SpongeCommonEventFactory.class:1.10.2-5.2.0-BETA-385]
    at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:449) ~[SpongeCommonEventFactory.class:1.10.2-5.2.0-BETA-385]
    at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(SourceFile:616) ~[lv.class:?]
    at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zgp000(SourceFile:2003) ~[me.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_184337_a(SourceFile:627) ~[me.class:?]
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
    at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-5.2.0-BETA-385]
    at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160) [CauseTracker.class:1.10.2-5.2.0-BETA-385]
    at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-5.2.0-BETA-385]
    at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:539) [fl$1.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
    at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239) [SpongeImplHooks.class:1.10.2-5.2.0-BETA-385]
    at net.minecraft.server.MinecraftServer.redirect$onRun$zhj000(SourceFile:4153) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1499) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by JimiIT92** [comment]
Will look into it as soon as i can (unfortunatley my pc is in assistance right now so i had to wait until is repaired :/ )

**Comment by JimiIT92** [comment]
Should be fixed in the next release
