### ISSUE TITLE
Sponge/UG issues

### ISSUE THREAD

**Issue by sfxworks** [JimiIT92/UniverseGuard#15]
I get these errors spamming console at random times.

```
[20:00:30] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Primary$MainHand$Impl to Plugin{id=universeguard, name=Universe Guard 2, version=2.3, description=An easy to use world protection plugin for Sponge, authors=[Minehendrix], source=/./mods/plugins/UniverseGuard-2.3.jar}
java.lang.NoClassDefFoundError: org/spongepowered/api/data/meta/ItemEnchantment
        at com.universeguard.utils.InventoryUtils.getSelector(InventoryUtils.java:37) ~[InventoryUtils.class:?]
        at com.universeguard.utils.InventoryUtils.isSelector(InventoryUtils.java:49) ~[InventoryUtils.class:?]
        at com.universeguard.event.EventRegionSelect.setPoint(EventRegionSelect.java:62) ~[EventRegionSelect.class:?]
        at com.universeguard.event.EventRegionSelect.onRightClick(EventRegionSelect.java:39) ~[EventRegionSelect.class:?]
        at org.spongepowered.common.event.listener.MainHandListener_EventRegionSelect_onRightClick153.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-3002]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-3002]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:312) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-3002]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:364) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-3002]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427) [SpongeEventManager.class:1.12.2-2611-7.1.0-BETA-3002]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-3002]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventPrimary(SpongeCommonEventFactory.java:702) [SpongeCommonEventFactory.class:1.12.2-2611-7.1.0-BETA-3002]
        at net.minecraft.server.MinecraftServer.handler$onServerTickEnd$zjm000(MinecraftServer.java:3834) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:711) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by sfxworks** [comment]
Sorry! Will apply patch tonight. Thanks!
