### ISSUE TITLE
 Could not pass SpawnEntityEvent - Server error upon startup

### ISSUE THREAD

**Issue by bhi-elliot** [JimiIT92/UniverseGuard#5]
Good day,

Thank you for this mod.
I received this server error when I started the server. Not sure what would have caused it.
Not sure if this is helpful. Hopefully!

Let me know if you need any more info.

```
[Server thread/ERROR] [Sponge]: Could not pass SpawnEntityEvent$ChunkLoad$Impl to Plugin{id=universeguard, name=Universe Guard, version=1.0, description=A World Guard solution for Sponge, authors=[Minehendrix], source=C:\Minecraft_Server\mods\UniverseGuard.jar}
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[?:1.8.0_144]
        at com.universeguard.utils.RegionUtils.load(RegionUtils.java:199) ~[RegionUtils.class:?]
        at com.universeguard.utils.RegionUtils.getAllRegions(RegionUtils.java:42) ~[RegionUtils.class:?]
        at com.universeguard.utils.RegionUtils.load(RegionUtils.java:73) ~[RegionUtils.class:?]
        at com.universeguard.events.flags.EventSpawnEntity.onEntitySpawn(EventSpawnEntity.java:17) ~[EventSpawnEntity.class:?]
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_EventSpawnEntity_onEntitySpawn109.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2393-6.1.0-BETA-2484]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2393-6.1.0-BETA-2484]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2393-6.1.0-BETA-2484]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2393-6.1.0-BETA-2484]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2393-6.1.0-BETA-2484]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) [SpongeImpl.class:1.11.2-2393-6.1.0-BETA-2484]
        at net.minecraft.world.WorldServer.handler$spongeLoadEntities$zkf000(WorldServer.java:2584) [lw.class:?]
        at net.minecraft.world.WorldServer.func_175650_b(WorldServer.java) [lw.class:?]
        at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:844) [auo.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:104) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:119) [lv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:90) [lv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunkForce(ChunkProviderServer.java:1075) [lv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.redirect$onProvideChunkHead$zkn000(ChunkProviderServer.java:680) [lv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:136) [lv.class:?]
        at net.minecraft.server.MinecraftServer.prepareSpawnArea(MinecraftServer.java:3563) [MinecraftServer.class:?]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:824) [WorldManager.class:1.11.2-2393-6.1.0-BETA-2484]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:770) [WorldManager.class:1.11.2-2393-6.1.0-BETA-2484]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3511) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:267) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by JimiIT92** [comment]
Thank you for the report, will look into this problem and fix it as soon as possible ;)

**Comment by JimiIT92** [comment]
EDIT: It looks like you are using the 1.0 version, try using the updated version (1.0.4) available [here](https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard/versions/1.0.4). (If this link doesn't work try this -> [https://mega.nz/#!VINgSDpC!OPWPmYX_CII_jNWJXJAWfnC-vPuyEFpubb6QpMqJlgE](https://mega.nz/#!VINgSDpC!OPWPmYX_CII_jNWJXJAWfnC-vPuyEFpubb6QpMqJlgE))

**Comment by bhi-elliot** [comment]
Ah, thanks for the reply and for the link. I like when mods/plugins have the version number right in the filename (the one on your Sponge forum link does not include the version). Thanks!

Running it and so far have not received the same message. I'll let you know if I see it back.

Much appreciated.

**Comment by JimiIT92** [comment]
Glad to know it, unfortunately i'm having some issues with Ore and i hope to solve them soon
