### ISSUE TITLE
[1.10] NoClassDefFoundError: LocatableBlock

### ISSUE THREAD

**Issue by Santana1053** [JimiIT92/UniverseGuard#9]
Error occurs when breaking any block in Botania using spongeforge-1.10.2-2123-6.0.0-BETA-1902
```[13:18:50] [Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Break$Impl to Plugin{id=universeguard, name=UniverseGuard, version=1.0.5, description=A World Guard solution for Sponge, aut[0/1295]nehendrix], source=/home/gameservers/alice_1-10_refresh/mods/$ponge_UniverseGuard-1.0.5.jar}
java.lang.NoClassDefFoundError: org/spongepowered/api/world/LocatableBlock
        at com.universeguard.events.flags.EventBlockBreak.onBlockBreakByEntity(EventBlockBreak.java:27) ~[EventBlockBreak.class:?]
        at org.spongepowered.common.event.listener.BreakListener_EventBlockBreak_onBlockBreakByEntity75.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357) ~[SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:398) ~[SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) ~[SpongeModEventManager.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:144) ~[SpongeImpl.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:583) ~[TrackingUtil.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:503) ~[TrackingUtil.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$null$23(PacketFunction.java:425) ~[PacketFunction.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57) ~[CapturedSupplier.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$28(PacketFunction.java:424) ~[PacketFunction.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) [PacketPhase.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2123-6.0.0-BETA-1902]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:140) [PacketUtil.class:1.10.2-2123-6.0.0-BETA-1902]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by JimiIT92** [comment]
Will look into it as soon as possible ;)

**Comment by Santana1053** [comment]
It's not a huge issue, since I using an experimental version of APIv6 for 1.10 which hasn't been updated in 9 months, and I'm not using it anymore.
